apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  backend_groovy.sh: |
    @GrabConfig(systemClassLoader=true)
    @Grab(group='org.postgresql', module='postgresql', version='9.4-1205-jdbc42')
    @Grab('io.ratpack:ratpack-groovy:1.6.0')
    @Grab('org.slf4j:slf4j-simple:1.7.25')

    import groovy.sql.Sql
    import static ratpack.groovy.Groovy.ratpack

    println "Starting the backend ..."

    def env = System.getenv()
    def dbUrl      = "jdbc:postgresql://${env['POSTGRES_HOST']}/${env['POSTGRES_DB']}"
    def dbUser     = env['POSTGRES_USER']
    def dbPassword = env['POSTGRES_PASSWORD']
    def dbDriver   = "org.postgresql.Driver"

    println "Connecting to ${dbUrl} with user ${dbUser}"
    def sql = Sql.newInstance(dbUrl, dbUser, dbPassword, dbDriver)

    ratpack {
        handlers {
            get {
               def rows = sql.rows('select count(*) from pg_stat_activity')
               render "${rows[0]} from ${env['HOSTNAME']}"
            }
        }
    }
