apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: groovy
        imagePullPolicy: IfNotPresent
        name: backend
        args: ['groovy', '/scripts/backend_groovy.sh']
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret
        envFrom:
        - configMapRef:
            name: postgres-config
        livenessProbe:
          httpGet:
            path: /
            port: 5050
            scheme: HTTP
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 5050
            scheme: HTTP
          initialDelaySeconds: 60
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: scripts
          configMap:
            name: backend-config
            defaultMode: 0744
