apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    run: postgres
  name: postgres
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      run: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - image: postgres:10
        imagePullPolicy: IfNotPresent
        name: postgres
        args: ['-c', 'shared_buffers=256MB', '-c', 'max_connections=200']
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres
