apiVersion: v1
data:
  POSTGRES_HOST: postgres
  POSTGRES_USER: test
  POSTGRES_DB: test
  PGDATA: /var/lib/postgresql/data/pgdata
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
